---
# This role contains tasks for configuring and starting netmaster and netplugin service

# Install ovs, needed for our netplugin deployments.
- include: ovs.yml

- name: for legacy install, extract all binaries
  shell: tar vxjf {{ contiv_network_dest_file }}
  args:
    chdir: /usr/bin/contiv/netplugin

- name: create links for netplugin binaries
  file: src=/usr/bin/contiv/netplugin/{{ item }} dest=/usr/bin/{{ item }} state=link force=yes
  with_items:
    - netmaster
    - netplugin
    - contivk8s

- name: copy environment file for netplugin
  template: src=netplugin.j2 dest=/etc/default/netplugin

- name: copy systemd units for netplugin
  copy: src=netplugin.service dest=/etc/systemd/system/netplugin.service

- name: start netplugin
  systemd: name=netplugin daemon_reload=yes state=started enabled=yes

# XXX: remove this task once the following is resolved: https://github.com/contiv/netplugin/issues/275
- name: setup hostname alias
  lineinfile:
    dest: /etc/hosts
    line: "{{ item.line }}"
    regexp: "{{ item.regexp }}"
    state: present
  with_items:
    - { line: '127.0.0.1 localhost', regexp: '^127\.0\.0\.1 .*localhost$' }
    - { line: '{{ node_addr }} {{ ansible_hostname }}', regexp: ' {{ ansible_hostname }}$' }

- name: copy environment file for netmaster
  template: src=netmaster.j2 dest=/etc/default/netmaster
  when: run_as == "master"

- name: copy systemd units for netmaster
  copy: src=netmaster.service dest=/etc/systemd/system/netmaster.service
  when: run_as == "master"

- name: start netmaster
  systemd: name=netmaster daemon_reload=yes state=started enabled=yes
  when: run_as == "master"
