# netplugin-master hosts set up netmaster and rest as netplugin
- name: Install Contiv to Master
  hosts: netplugin-master
  become: true
  environment: '{{ env }}'
  roles:
    - { role: contiv_network, scheduler_provider: native-swarm, run_as: master }
- name: Install Contiv to Workers
  hosts: netplugin-worker
  become: true
  environment: '{{ env }}'
  roles:
    - { role: contiv_network, scheduler_provider: native-swarm, run_as: worker }
