# netplugin-master hosts set up netmaster nodes
- name: Install etcd to master
  hosts: netplugin-master
  become: true
  environment: '{{ env }}'
  roles:
    - { role: etcd, run_as: master }

- name: Install etc to worker
  hosts: netplugin-worker
  become: true
  environment: '{{ env }}'
  roles:
    - { role: etcd, run_as: worker }
